# Generated by Django 4.0.3 on 2022-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('repo', models.CharField(max_length=1000, verbose_name='ссылка на репозиторий')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_todo', models.TextField(max_length=4000, verbose_name='текст заметки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
        ),
    ]
